- name: Install Brave browser
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install dnf-plugins-core dependency
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: latest
    - name: Add brave repo to dnf
      ansible.builtin.shell: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    - name: Import brave core to rpm
      ansible.builtin.shell: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    - name: Install brave
      ansible.builtin.dnf:
        name: brave-browser
        state: latest